### ISSUE TITLE
Cygwin64 compile error

### ISSUE THREAD

**Issue by 276585877** [rgcjonas/dd4seven#1]
CXX(amd64,debug) src/dd4seven-api.cpp
CXX(amd64,debug) src/logger.cpp
WINDRES(amd64,debug) out/amd64/debug/src/dd4seven-api.dll.rc
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-windres --codepage=65001 -o out/amd64/debug/src/dd4seven-api.dll.rc.o out/amd64/debug/src/dd4seven-api.dll.rc, ...) failed.
make: *** [Makefile:101: out/amd64/debug/dd4seven-api.dll] Error 2

**Comment by rgcjonas** [comment]
Cygwin is not officially supported. You can try and I'll accept a pull request if you figure out how to do it, but you're on your own. Please cross-compile from linux, I'll try assist you if there are problems with the cross-compiling approach.

**Comment by BillFleming** [comment]
Any tips or mini-guide on cross-compiling this from Linux? Do you take beer donations?

**Comment by rgcjonas** [comment]
I compiled it on my new fedora install a few minutes ago. This were the steps I took:

* I needed to install `mingw64-gcc-c++ mingw32-gcc-c++ mingw64-winpthreads-static mingw32-winpthreads-static`. Your distro of choice might be different, but it should be possible to figure out the dependencies from the compiler error messages.

* There is a `Makefile`. I originally wanted to claim that it works, but I discovered that it is a little buggy. It wanted to regenerate the D3D headers and complained about missing `*-widl`, I then had to run `make clean` and then `make` again to make it work.

I like beer, but I'm much more curious about what you're planning to do with the thing. So If you don't mind, please tell me about what you're building :smile:  And always remember, this is not production quality code, you should thoroughly review and improve it before shipping.

**Comment by BillFleming** [comment]
Jonas,

There is some interest in getting the looking glass software running in
Windows 7 for GPU passthrough. Also there are some other pieces of software
out there (streaming, etc) where the project could be useful if we can get
it working. (For example, there is fiber going into the ground everywhere
where I live which will bring many opportunities for things)
Note that in the case of looking glass the software is buggier then your
project, from what they claim.

With my current VM setup, it can automatically pass in mobo audio, 4 USB 3
ports (and whatever is plugged into them) directly into the VM along with
the GPU.
When I shutdown the VM, the devices automagically work again in the host.
(now that bugs were fixed related to VEGA GPUs)
But today I have to use a second monitor to switch physical ports to the
second GPU.
But with looking glass you could run the display through a client app on
the host. (or remote location if you have speed and/or run encoding on
picture first)

https://forum.level1techs.com/t/looking-glass-guides-help-and-support/122387
https://looking-glass.hostfission.com/quickstart

So on my Kubuntu system I followed the following method for prereqs (didn't
know before they had mingw packages shipped with distros):
sudo apt install g++-mingw-w64 g++-mingw-w64-i686  gcc-mingw-w64
gcc-mingw-w64-i686 libnpth-mingw-w64-dev

Then running make it actually worked on the first try unlike your
experience. (see google drive below for compile output)

Then for looking class client:
sudo apt-get install cmake libsdl2-dev libsdl2-ttf-dev libssl-dev
libspice-protocol-dev libfontconfig1-dev libx11-dev fonts-freefont-ttf
libconfig-dev nettle-dev

For memdevice for libvirt:
touch /dev/shm/looking-glass
sudo chown libvirt-qemu /dev/shm/looking-glass
sudo chmod 660 /dev/shm/looking-glass

Then I added the memdevice xml to my VM using virsh edit.

Then in windows 7 VM Install the IVSHMEM driver from
virtio-win10-prewhql-0.1-161.zip
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/

However trying to run the host application I get the following error, but I
can run your test.dx11.exe just fine.
So there is some DXGI functionality missing. See the screenshot in the
google drive for the MFCreateDXGIDeviceManager error.

https://drive.google.com/open?id=14ZKnuCX-YPK8t3awz-5NwoVl6vJteBmy

Here is my example setup for GPU passthrough with VEGA on X370 mobo. I just
got the bugs worked out so that I can plug GPUs in where I want. New kernel
and libvirt packages were needed to fix those bugs.
https://forum.level1techs.com/t/vfio-example-primary-slot-vega-passthrough-now-works-vega-reset-issue-fixed-for-good/131933

Here was the make output:

> bill@Bill-X370:~/Software/dd4seven-master$
> make
>
> CXX(amd64,debug)
> src/dd4seven-api.cpp
>
> CXX(amd64,debug)
> src/logger.cpp
>
> WINDRES(amd64,debug)
> out/amd64/debug/src/dd4seven-api.dll.rc
>
> LD(amd64,debug)
> out/amd64/debug/dd4seven-api.dll
>
> CXX(amd64,release)
> src/dd4seven-api.cpp
>
> CXX(amd64,release)
> src/logger.cpp
>
> WINDRES(amd64,release)
> out/amd64/release/src/dd4seven-api.dll.rc
>
> LD(amd64,release)
> out/amd64/release/dd4seven-api.dll
>
> CXX(x86,release)
> src/dd4seven-api.cpp
>
> CXX(x86,release)
> src/logger.cpp
>
> WINDRES(x86,release)
> out/x86/release/src/dd4seven-api.dll.rc
>
> LD(x86,release)
> out/x86/release/dd4seven-api.dll
>
> CXX(x86,debug)
> src/dd4seven-api.cpp
>
> CXX(x86,debug)
> src/logger.cpp
>
> WINDRES(x86,debug) out/x86/debug/src/dd4seven-api.dll.rc
> LD(x86,debug) out/x86/debug/dd4seven-api.dll
> CXX(amd64,debug) src/dd4seven-dwm.cpp
> CC(amd64,debug) minhook/src/hook.c
> CC(amd64,debug) minhook/src/hde/hde32.c
> CC(amd64,debug) minhook/src/hde/hde64.c
> CC(amd64,debug) minhook/src/buffer.c
> CC(amd64,debug) minhook/src/trampoline.c
> WINDRES(amd64,debug) out/amd64/debug/src/dd4seven-dwm.dll.rc
> LD(amd64,debug) out/amd64/debug/dd4seven-dwm.dll
> CXX(amd64,release) src/dd4seven-dwm.cpp
> CC(amd64,release) minhook/src/hook.c
> CC(amd64,release) minhook/src/hde/hde32.c
> CC(amd64,release) minhook/src/hde/hde64.c
> CC(amd64,release) minhook/src/buffer.c
> CC(amd64,release) minhook/src/trampoline.c
> WINDRES(amd64,release) out/amd64/release/src/dd4seven-dwm.dll.rc
> LD(amd64,release) out/amd64/release/dd4seven-dwm.dll
> CXX(x86,release) src/dd4seven-dwm.cpp
> CC(x86,release) minhook/src/hook.c
> CC(x86,release) minhook/src/hde/hde32.c
> CC(x86,release) minhook/src/hde/hde64.c
> CC(x86,release) minhook/src/buffer.c
> CC(x86,release) minhook/src/trampoline.c
> WINDRES(x86,release) out/x86/release/src/dd4seven-dwm.dll.rc
> LD(x86,release) out/x86/release/dd4seven-dwm.dll
> CXX(x86,debug) src/dd4seven-dwm.cpp
> CC(x86,debug) minhook/src/hook.c
> CC(x86,debug) minhook/src/hde/hde32.c
> CC(x86,debug) minhook/src/hde/hde64.c
> CC(x86,debug) minhook/src/buffer.c
> CC(x86,debug) minhook/src/trampoline.c
> WINDRES(x86,debug) out/x86/debug/src/dd4seven-dwm.dll.rc
> LD(x86,debug) out/x86/debug/dd4seven-dwm.dll
> CXX(amd64,debug) src/test-dx11.cpp
> WINDRES(amd64,debug) out/amd64/debug/src/test-dx11.exe.rc.o
> LD(amd64,debug) out/amd64/debug/test-dx11.exe
> CXX(amd64,release) src/test-dx11.cpp
> WINDRES(amd64,release) out/amd64/release/src/test-dx11.exe.rc.o
> LD(amd64,release) out/amd64/release/test-dx11.exe
> CXX(x86,release) src/test-dx11.cpp
> WINDRES(x86,release) out/x86/release/src/test-dx11.exe.rc.o
> LD(x86,release) out/x86/release/test-dx11.exe
> CXX(x86,debug) src/test-dx11.cpp
> WINDRES(x86,debug) out/x86/debug/src/test-dx11.exe.rc.o
> LD(x86,debug) out/x86/debug/test-dx11.exe
>
>
I haven't looked through the looking glass code yet but there are probably
only a few missing functions that we need to implement. That might be worth
the beer money right?

Bill
